# Generated by Django 5.0.2 on 2024-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_rating', models.IntegerField(default=0, help_text='Rating out of 10 for the training')),
                ('trainer_rating', models.IntegerField(default=0, help_text='Rating out of 10 for the trainer')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
